### ISSUE TITLE
Lava spills out everywhere

### ISSUE THREAD

**Issue by scr267** [HeroOfTheWinds/minetest-caverealms#16]
In mapgen V6, caverealms creates caves without taking into consideration the smaller caves that get generated by V6 - these contain lava and these spill in the larger caverealms caves.

**Comment by HeroOfTheWinds** [comment]
Last I knew, mapgen V6 generated lava and water in its caves *after* the Lua Voxel Manipulator runs, hence making it impossible to tell where and when mgv6 will create lava.  Hence, this can't really be fixed without running a post-mgv6 exhaustive search of the map chunk, which adds more overhead to map generation than needed or wanted.
Really, a way to turn off lava generation in the base game mapgens would be really nice...

Thanks for the comment though, sorry there isn't much I can do.  I'm sure a separate mod could be made to scan for and remove lava, just be aware of the overhead on load time (especially on servers) that will generate.
